name: ci
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: latest

      - name: Run build
        run: mdbook build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: book

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    #if: github.ref == 'refs/heads/master'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: .
